# Components for bounded context: Seller
# Included by workspace.dsl into the `seller` container.
seller_registersellerusecase = component "RegisterSellerUseCase" "inbound use-case port" "port.in"
seller_sellerrepository = component "SellerRepository" "outbound port" "port.out"
seller_displayname = component "DisplayName" "aggregate / value object" "domain"
seller_email = component "Email" "aggregate / value object" "domain"
seller_seller = component "Seller" "aggregate / value object" "domain"
seller_sellerid = component "SellerId" "aggregate / value object" "domain"
seller_sellerstatus = component "SellerStatus" "aggregate / value object" "domain"
seller_registersellerusecase -> seller_displayname "handles"
seller_registersellerusecase -> seller_email "handles"
seller_registersellerusecase -> seller_seller "handles"
seller_registersellerusecase -> seller_sellerid "handles"
seller_registersellerusecase -> seller_sellerstatus "handles"
seller_displayname -> seller_sellerrepository "persists via"
seller_email -> seller_sellerrepository "persists via"
seller_seller -> seller_sellerrepository "persists via"
seller_sellerid -> seller_sellerrepository "persists via"
seller_sellerstatus -> seller_sellerrepository "persists via"
