"""Render a DesignSpec into explicit, reviewable Markdown artifacts (M07):
one **Architecture Description** (umbrella) + one **Tech Spec per bounded context**
(1 BC = 1 Tech Spec). Pure functions over domain models — no I/O, no infra — so
they live in the application layer; the orchestrator writes the strings out via the
git tool, and an architect reviews them at the approval gate before coding.
"""

from __future__ import annotations

import re

from aicoder.domain.models import DesignSpec, TechSpec

_DOCS_SUBDIR = "docs/design"


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return s or "context"


def tech_spec_path(ts: TechSpec, docs_dir: str = _DOCS_SUBDIR) -> str:
    return f"{docs_dir}/techspec-{_slug(ts.bounded_context)}.md"


def ad_path(docs_dir: str = _DOCS_SUBDIR) -> str:
    return f"{docs_dir}/AD.md"


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "_(none)_"


def render_ad(spec: DesignSpec, requirement: str, docs_dir: str = _DOCS_SUBDIR) -> str:
    """The umbrella Architecture Description: the change at system level + the list
    of bounded contexts, each linking to its Tech Spec."""
    bc_rows = "\n".join(
        f"- **{ts.bounded_context}** → [`{tech_spec_path(ts, docs_dir).split('/')[-1]}`]"
        f"({tech_spec_path(ts, docs_dir).split('/')[-1]}) — {ts.summary}"
        for ts in spec.tech_specs
    ) or "_(none)_"
    return (
        f"# Architecture Description\n\n"
        f"> Generated by the design phase for one change; reviewed by an architect "
        f"before implementation. One AD spans one or more Tech Specs — **1 bounded "
        f"context = 1 Tech Spec**.\n\n"
        f"## Requirement\n{requirement}\n\n"
        f"## Summary\n{spec.summary}\n\n"
        f"## Cross-cutting decisions\n{_bullets(spec.decisions)}\n\n"
        f"## Bounded contexts (→ Tech Specs)\n{bc_rows}\n"
    )


def render_tech_spec(ts: TechSpec) -> str:
    """The technical specification for one bounded context."""
    tests = "\n".join(
        f"- `{t.path}` — {t.rationale or 'acceptance test'}" for t in ts.test_plan
    ) or "_(none)_"
    return (
        f"# Tech Spec — {ts.bounded_context}\n\n"
        f"## Summary\n{ts.summary}\n\n"
        f"## Affected components\n{_bullets(ts.affected)}\n\n"
        f"## Interface / contract changes\n{_bullets(ts.interface_changes)}\n\n"
        f"## Decisions / notes\n{ts.adr_notes or '_(none)_'}\n\n"
        f"## Acceptance tests (the locked oracle)\n{tests}\n"
    )
